name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compile
        run: echo Building

  DeployDev:
    name: Deploy to Dev
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: ''
    steps:
      - name: Deploy
        run: echo Deploying to Development

  DeployStaging:
    name: Deploy to Staging
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: ''
    steps:
      - name: Deploy
        run: echo Staging

  DeployProd:
    name: Deploy to Production
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'https://discord.com/api/oauth2/authorize?client_id=1104960590327333016&permissions=70368744177399&scope=applications.commands%20bot'
    steps:
      - name: Deploy
        run: echo Connecting to Google Cloud VM Instance...
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.GCLOUD_IP}}
          username: ${{secrets.GCLOUD_USERNAME}}
          key: ${{secrets.GCLOUD_SSH}}
          script: |
            PATH=$PATH:/home/${{secrets.GCLOUD_USERNAME}}/.nvm/versions/node/v18.16.0/bin
            cd Production
            ./apollo.sh -lscFGLr
